### PR TITLE
Adds converter for formatted email address

### PR DESCRIPTION
**Pull request by ghost**
The current converter for email addresses uses to_s in the serialize function, this converter uses the newly added `.format` to retain the entire email address

### CODE REVIEW

**Review by grantspeelman — COMMENTED** [review]
Nice 👍🏽 
Can you add a spec for it like the others : https://github.com/NEXL-LTS/rails_values/blob/main/spec/rails_values/email_address_active_model_converter_spec.rb

**Comment by ghost** [comment]
> Nice 👍🏽 Can you add a spec for it like the others : https://github.com/NEXL-LTS/rails_values/blob/main/spec/rails_values/email_address_active_model_converter_spec.rb

@grantspeelman err yep - thanks - I have added it

**Review by bapu-nexl — APPROVED** [review]
good work 👍

**Review by grantspeelman — COMMENTED** [review]
Great Work 👍🏽

**Pull request merged**
